<?php

/**
 * PluginstPicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage stGalleryPlugin
 * @author     Miloslav Kmeť <miloslav.kmet@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginstPicture extends BasestPicture
{
    protected $thumbnailGenerated = false;
    
    protected $imageGeneated = false;
    
    protected $tableizedRecordClass = false;
    
    public function getTableizedRecordClass()
    {
        if ($this->tableizedRecordClass === false)
        {
            $this->tableizedRecordClass = Doctrine_Inflector::tableize($this->record_model);
        }
        
        return $this->tableizedRecordClass;
    }
    
    public function getConfig($section, $key, $default=null)
    {
        if (($tb = $this->getTableizedRecordClass()) !== null)
        {
            return sfConfig::get('st_gallery_'.$tb.'_'.$section.'_'.$key, sfConfig::get('st_gallery_'.$section.'_'.$key, $default));
        }
        return sfConfig::get('st_gallery_'.$section.'_'.$key, $default);
    }
    
    public function isPublished()
    {
        return $this->is_published;
    }
    
    public function publish()
    {
        $this->is_published = true;
    }
    
    public function unpublish()
    {
        $this->is_published = false;
    }
    
    public function setSource($image)
    {
        if (is_file($image))
        {
            $webDir = sfConfig::get('sf_web_dir');
            $image = preg_replace('~^'.preg_quote(sfConfig::get('sf_web_dir')).'~', '', $image);
        }
        $this->_set('source', $image);
        
        return $this;
    }
    
    public function preDelete($event)
    {
        $this->removeFile('image');
        $this->removeFile('thumbnail');
        $this->removeFile('source');
    }
    
    public function postInsert($event)
    {
        $thumbnail = $this->generateThumbnail();
        $image     = $this->generateImage();
         
        if ($thumbnail || $image)
        {
            $this->save();
        }
    }
    
    /**
     * Returns the parameter value or null
     * 
     * @param $param mixed name of the option
     * 
     * @return mixed
     */
    public function getParamValue($param)
    {
        return isset($this->params[$param]) ? $this->params[$param] : null;
    }
    
    /**
     * Sets the parameter value
     * 
     * @param $param mixed name or index of the option
     * @param $vlaue mixed parameter value
     * 
     * @return stPicture instance of this class
     */
    public function setParamValue($param, $value)
    {
        $params = $this->_get('params');
        if (!is_array($params) && $params !== null) {
            $params = array($params);
        }
        
        $params[$param] = $value;
        
        $this->_set('params', $params);
        
        return $this;
    }
    
    /**
     *
     */
    protected function getFilePath($source, $column)
    {
        $dirName = dirname($source);
        $ext = strrchr(basename($source), '.');
        
        return $dirName . DIRECTORY_SEPARATOR
             . $this->getConfig($column, 'prefix', null)
             . sprintf('%06d', $this->id)
             . $this->getConfig($column, 'suffix', '_'.$column)
             . $ext;
    }
    
    protected function getSourcePicture()
    {
        $source = $this->getSource();
        if (empty($source))
        {
            $source = $this->getImage();
        }
        
        return $source;
    }
    
    /**
     * Generates image from source only if source exists and object is already persisted in database
     * 
     * @return boolean true on succes, otherwise false
     */
    protected function generateImage()
    {
        // cannot generate image on not persisted pictures
        if ($this->_state === self::STATE_TDIRTY)
        {
            throw new RuntimeException('Can not generate image on not persisted picture.');
        }
        
        $source = $this->getSource();
        
        // cannot generate if the source does not exist
        if (empty($source) || !is_file(sfConfig::get('sf_web_dir').$source))
        {
            return false;
        }
        
        $maxWidth  = $this->getParamValue('max_width') ?
            $this->getParamValue('max_width') : $this->getConfig('image', 'max_width', null);
            
        $maxHeight  = $this->getParamValue('max_height') ? 
            $this->getParamValue('max_height') : $this->getConfig('image', 'max_height', null);
            
        $image = new sfImage(sfConfig::get('sf_web_dir').$source);
        
        // resize image if necessary
        if ($maxWidth !== null && $maxWidth < $image->getWidth())
        {
            $image->resize($maxWidth, null, false, true);
        }

        if ($maxHeight !== null && $maxHeight < $image->getHeight())
        {
            $image->resize(null, $maxHeight, false, true);
        }
        
        // add overlay if necessary
        $overlay = $this->getConfig('image', 'overlay', null);
        
        if ($overlay !== null && is_file($overlay))
        {
            $position = $this->getParamValue('overlay_position') ?
                $this->getParamValue('overlay_position') : $this->getConfig('image', 'overlay_position', 'top-right');
            
            if ($position !== 'none' && $position !== null)
            {
                $image->overlay(new sfImage($overlay), $position);
            }
        }
               
        
        // saving file
        $relativeFile = $this->getFilePath($source, 'image'); 
        $image->saveAs(sfConfig::get('sf_web_dir').$relativeFile);

        $this->set('image', $relativeFile);
        
        return true;
    }
    
    /**
     * Generates thumbnail from source only if the class already persists in the database
     * 
     * @return boolean true on success, false on failure
     */
    protected function generateThumbnail()
    {
        // cannot generate thumbnails on not persisted pictures
        if ($this->_state === self::STATE_TDIRTY)
        {
            throw new RuntimeException('Can not generate thumbnail on not persisted pictue');
        }
        
        $source = $this->getSourcePicture();
        
        if (!is_file(sfConfig::get('sf_web_dir').$source))
        {
            return false; 
        }
        
        $modelPrefix = Doctrine_Inflector::tableize($this->record_model);

        $width  = $this->getParamValue('thumbnail_width') ? 
            $this->getParamValue('thumbnail_width') : $this->getConfig('thumbnail', 'width', 144);
            
        $height  = $this->getParamValue('thumbnail_height') ?
            $this->getParamValue('thumbnail_height') : $this->getConfig('thumbnail', 'height', 108);
        
        $method = $this->getParamValue('thumbnail_method') ? 
            $this->getParamValue('thumbnail_method') : $this->getConfig('thumbnail', 'method', 'center');
        
        $quality = $this->getParamValue('thumbnail_quality') ?
            $this->getParamValue('thumbnail_quality') : $this->getConfig('thumbnail', 'quality', 80);
            
        $image = new sfImage(sfConfig::get('sf_web_dir').$source);
        
        $thumb = $image->thumbnail($width, $height, $method);
        
        $thumb->setQuality($quality);
        
        $relativeFile = $this->getFilePath($source, 'thumbnail');
        
        $thumb->saveAs(sfConfig::get('sf_web_dir').$relativeFile);
        
        $this->set('thumbnail', $relativeFile);
        
        return true;
    }

    /**
     * Remove files for columns from filesystem
     * 
     * @param string column
     * 
     * @return $this
     */
    protected function removeFile($column)
    {
        $file = $this->get($column);
        if (!empty($file) && is_file($file = sfConfig::get('sf_web_dir').$file))
        {
            unlink($file);
        }
        
        $this->set($column, null);
        
        return $this;
    }
}