<?php

/**
 * PluginstPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginstPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginstPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginstPicture');
    }
    
    public function findAllForRecord(Doctrine_Record $record)
    {
        return $this->createQuery('p')
            ->addWhere('p.record_model = ?', get_class($record))
            ->addWhere('p.record_id = ?', $record->get($record->getTable()->getIdentifier()))
            ->execute();
    }
}